### ISSUE TITLE
慢

### ISSUE THREAD

**Issue by zhenrenbumeng** [zzerding/aardio-log4j#5]
如下图，我原本用console执行一次31ms，改为logger后变成了70ms，内容也不多，有没有办法优化一下能够不影响原本的执行时间？

![image](https://github.com/zzerding/aardio-log4j/assets/136045810/6d585663-8d69-4343-babb-cc39fb57a857)

**Comment by zzerding** [comment]
这个日志在新开线程里运行涉及到线程锁定和线程通讯，你这个计算方式也不准确，你得把变量控制一下在测试是不是真的慢了30ms。
